import { prisma } from '../../config/database.js'
import { logger } from '../../lib/logger.js'
import { llmChat } from './client.js'
import { REMEDIATION_SYSTEM_PROMPT, buildRemediationPrompt } from './prompts.js'
import { broadcastToOrg } from '../../routes/websocket.js'

export interface RemediationResult {
  summary: string
  files: Array<{
    path: string
    language: string
    diff: string
    fullFixed: string
  }>
  explanation: string
  testSuggestion: string
  breakingChanges: boolean
  estimatedRisk: 'low' | 'medium' | 'high'
}

/**
 * Generate a remediation patch for a vulnerability using LLM.
 * Updates the remediation record with the result.
 */
export async function generateRemediation(remediationId: string): Promise<void> {
  const remediation = await prisma.remediation.findUnique({
    where: { id: remediationId },
    include: {
      vulnerability: {
        include: {
          target: { select: { value: true, type: true } },
        },
      },
    },
  })

  if (!remediation) {
    logger.error({ remediationId }, 'Remediation not found')
    return
  }

  if (remediation.status !== 'GENERATING') {
    logger.warn({ remediationId, status: remediation.status }, 'Remediation not in GENERATING state, skipping')
    return
  }

  const vuln = remediation.vulnerability
  const orgId = vuln.orgId

  try {
    logger.info({ remediationId, vulnTitle: vuln.title }, 'Starting remediation generation')

    // Build the prompt
    const userPrompt = buildRemediationPrompt({
      title: vuln.title,
      description: vuln.description,
      severity: vuln.severity,
      category: vuln.category,
      cwe: vuln.cwe,
      owasp: vuln.owasp,
      endpoint: vuln.endpoint,
      evidence: vuln.evidence,
      poc: vuln.poc,
      target: { value: vuln.target.value, type: vuln.target.type },
    })

    // Call LLM
    const response = await llmChat(REMEDIATION_SYSTEM_PROMPT, userPrompt, {
      temperature: 0.1, // Low temperature for deterministic code generation
      maxTokens: 4096,
      model: 'gpt-4o',
    })

    // Parse JSON response
    let result: RemediationResult
    try {
      // Extract JSON from potential markdown code blocks
      let content = response.content.trim()
      if (content.startsWith('```json')) {
        content = content.slice(7)
      }
      if (content.startsWith('```')) {
        content = content.slice(3)
      }
      if (content.endsWith('```')) {
        content = content.slice(0, -3)
      }
      result = JSON.parse(content.trim())
    } catch (parseError) {
      logger.error({ remediationId, content: response.content.slice(0, 500) }, 'Failed to parse LLM response as JSON')
      // Fallback: treat entire response as a patch
      result = {
        summary: `Fix for ${vuln.title}`,
        files: [{
          path: 'fix.patch',
          language: 'diff',
          diff: response.content,
          fullFixed: response.content,
        }],
        explanation: 'Generated remediation (raw format)',
        testSuggestion: 'Verify the vulnerability is no longer exploitable',
        breakingChanges: false,
        estimatedRisk: 'medium',
      }
    }

    // Calculate lines added/removed from diffs
    let totalAdded = 0
    let totalRemoved = 0
    for (const file of result.files) {
      const lines = file.diff.split('\n')
      totalAdded += lines.filter((l) => l.startsWith('+') && !l.startsWith('+++')).length
      totalRemoved += lines.filter((l) => l.startsWith('-') && !l.startsWith('---')).length
    }

    // Construct the full patch content
    const patchContent = result.files.map((f) => 
      `--- a/${f.path}\n+++ b/${f.path}\n${f.diff}`
    ).join('\n\n')

    // Build PR description
    const prDescription = [
      `## 🔒 Security Fix: ${vuln.title}`,
      '',
      `**Severity:** ${vuln.severity} | **CVSS:** ${vuln.cvss ?? 'N/A'}`,
      `**Category:** ${vuln.category}${vuln.cwe ? ` (${vuln.cwe})` : ''}`,
      '',
      '### What was vulnerable',
      result.explanation,
      '',
      '### Changes',
      result.summary,
      '',
      '### Risk Assessment',
      `- Breaking changes: ${result.breakingChanges ? '⚠️ Yes' : '✅ No'}`,
      `- Estimated risk: ${result.estimatedRisk}`,
      '',
      '### Suggested Test',
      result.testSuggestion,
      '',
      '---',
      '*Generated by PenAgent AI*',
    ].join('\n')

    // Generate branch name
    const branchName = `fix/${vuln.category.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${remediationId.slice(0, 8)}`

    // Update remediation record
    await prisma.remediation.update({
      where: { id: remediationId },
      data: {
        status: 'PR_OPEN',
        patch: patchContent,
        description: prDescription,
        branch: branchName,
        linesAdded: totalAdded,
        linesRemoved: totalRemoved,
      },
    })

    // Create notification
    await prisma.notification.create({
      data: {
        orgId,
        type: 'PR_OPENED',
        title: `Remediation ready: ${vuln.title}`,
        body: result.summary,
        metadata: {
          remediationId,
          vulnerabilityId: vuln.id,
          severity: vuln.severity,
          linesAdded: totalAdded,
          linesRemoved: totalRemoved,
        },
      },
    })

    // Audit log
    await prisma.auditLog.create({
      data: {
        orgId,
        action: 'remediation.generated',
        resource: 'remediation',
        resourceId: remediationId,
        metadata: {
          vulnTitle: vuln.title,
          tokensUsed: response.totalTokens,
          model: response.model,
          filesChanged: result.files.length,
        },
      },
    })

    // Broadcast real-time update
    broadcastToOrg(orgId, {
      type: 'remediation.ready',
      data: {
        remediationId,
        vulnerabilityId: vuln.id,
        summary: result.summary,
        severity: vuln.severity,
      },
    })

    logger.info({
      remediationId,
      tokensUsed: response.totalTokens,
      filesChanged: result.files.length,
      linesAdded: totalAdded,
      linesRemoved: totalRemoved,
    }, 'Remediation generated successfully')

  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error'
    logger.error({ remediationId, error: errorMessage }, 'Remediation generation failed')

    // Mark as failed
    await prisma.remediation.update({
      where: { id: remediationId },
      data: { status: 'FAILED', description: `Generation failed: ${errorMessage}` },
    })

    // Notify about failure
    await prisma.notification.create({
      data: {
        orgId,
        type: 'SYSTEM',
        title: `Remediation generation failed: ${vuln.title}`,
        body: errorMessage,
        metadata: { remediationId, vulnerabilityId: vuln.id },
      },
    })

    broadcastToOrg(orgId, {
      type: 'remediation.failed',
      data: { remediationId, vulnerabilityId: vuln.id, error: errorMessage },
    })
  }
}
